<?php
  
/**
* Implements look_permission().
*/

function form_example_permission(){

return array(
'submit form_example'=> array(
'title'=> t('Access form_example submissions'),
'description'=>t('Access the form_example submissions'),

),

'access form_example_submissions'=> array(
'title'=> t('Submit form example'),
'description'=>t('Submit the form_example form'),
 'restrict access' =>TRUE,  
),

) ;


}

/**
*Implements hook_menu ()
*/

function form_example_menu(){
  $items = array();
  $items ['form-example']= array(
  'title'=> ' Example Form',
  'type'=> MENU_NORMAL_ITEM,
  'access arguments'=> array('submit form_example'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('form_example_form'),
  );
  
  
  $items ['form-submissions']= array(
  'title'=> 'My Form Submissions',
  'type'=> MENU_NORMAL_ITEM,
  'access arguments'=> array('Access form_example submissions'),
  'page callback' => 'form_example_submissions',
 
  );


   return $items;
}

/**
* My example form.
*/
function form_example_form($form, &$form_state)
{

$form['mynumber']= array(
'#type' => 'textfield',
'#title' => t('Enter a number'),
'#size' => 10,
'#maxlength' => 10,
'#required'=>TRUE,
'#description' => t('Please enter a valid number'),
);
 $form['mytextfield']= array(
'#type' => 'textfield',
'#title' => t('Enter some text'),
'#size' => 60,
'#maxlength' => 128,
'#required'=>TRUE,

);

$form['mytext']= array(
'#type' => 'textarea',
'#title' => t('Enter more text'),
'#required'=>TRUE,
'#default_value' => '',
'#description' => t('Enter more text.'),
);

 $form['submit']=array(
 
 '#type' => 'submit',
 '#value' => t('Add item'),
 
 );
 
 return $form;
}


/**
*Validation handler for the form_example_form
*/

function form_example_form_validate($form, &$form_state)
{ //  print('<pre>'.print_r($form_state['values'],1).' </pre>');die(); 
if(!is_numeric($form_state['values']['mynumber'])){

form_set_error('mynumber', t('You have to enter a valid number'));
return FALSE;

}

   return TRUE;
}

/**
* Submit handler for the form_example_form. Inserts entry to database
*/

function form_example_form_submit($form, &$form_state)
{
$fe_id= db_insert('form_example')
->fields(array(
'mynumber' => $form_state['values']['mynumber'],
'mytextfield'=>$form_state['values']['mytextfield'],
'mytext'=>$form_state['values']['mytext'],
))
  ->execute();
  
  drupal_set_message(t('Your form entry has been added'));
}


/**
*view the form submissions
*/

function form_example_submissions()
{

    $results = db_query("SELECT *FROM(form_example)");
    $header = array(t('ID'), t('My Number'), t('My Textfield'),t('My Text'));
    $rows = array();
    
    foreach($results AS $result)
    {
      $rows[] = array(
    check_plain($result->fe_id),
     check_plain($result ->mynumber),
      check_plain($result ->mytextfield),
      check_markup($result->mytext),
      );
      
      
      
    
    }
  return theme('table', array('header' => $header, 'rows'=> $rows ));
}